### ISSUE TITLE
建议netutil优化一下将Body的读取和json序列化也做进去

### ISSUE THREAD

**Issue by uouuou** [duke-git/lancet#1]
```go
resp, err := netutil.HttpPost(url, header, queryParams)
	if err != nil {
		log.Fatal(err)
	}

	body, _ := ioutil.ReadAll(resp.Body)
	var info MyInfo
	err = json.Unmarshal(body, &info)
	if err != nil {
		log.Fatal(err.Error())
		return
	}
```
 - 这个是目前的HTTP请求方式，可以新增一个解析方法将结构体传入返回对应的数据感觉更好吧
 - 当然这个应该是独立的方法，有可能存在有些人并不是使用结构体进行解析

**Comment by duke-git** [comment]
> 

类似以下方法吗？

func ParseRespToStruct(resp *http.Response, obj interface{}) error {
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	return json.Unmarshal(body, obj)
}

**Comment by duke-git** [comment]
> ```go
> resp, err := netutil.HttpPost(url, header, queryParams)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	body, _ := ioutil.ReadAll(resp.Body)
> 	var info MyInfo
> 	err = json.Unmarshal(body, &info)
> 	if err != nil {
> 		log.Fatal(err.Error())
> 		return
> 	}
> ```
> 
> * 这个是目前的HTTP请求方式，可以新增一个解析方法将结构体传入返回对应的数据感觉更好吧
> * 当然这个应该是独立的方法，有可能存在有些人并不是使用结构体进行解析

v1.0.8版本：netutil/request.go, 已添加 ParseHttpResponse函数, 支持将http.Response解析成传入的interface值。

**Comment by uouuou** [comment]
牛逼，之后有什么问题在pr，我来更新一波，哈哈

**Comment by duke-git** [comment]
> 牛逼，之后有什么问题在pr，我来更新一波，哈哈

欢迎欢迎 😄
