### ISSUE TITLE
fileutil 添加 ZipAppendEntry

### ISSUE THREAD

**Issue by TheLastSunset** [duke-git/lancet#106]
已存在的 zip 文件添加文件或文件夹

**Comment by duke-git** [comment]
@TheLastSunset, 麻烦将问题描述清晰一些。

1. 如果是新特性ZipAppendEntry，是支持zip文件时将内容追加到已存在的压缩文件吗？如果是，可以自行实现相关功能，然后提PR。
2. 如果是fileutil.Zip函数的bug，可以描述清楚后，提PR修复。

**Comment by TheLastSunset** [comment]
@duke-git 是的，追加文件到已有压缩包

提了一个 pr 107，暂时单测未通过

**Comment by duke-git** [comment]
@TheLastSunset ,运行单测试，TestZipAndUnZipAndZipAppendEntry，TestListFileNames这两个case失败。

1. TestZipAndUnZipAndZipAppendEntry 184行报错，这个测试函数过度复杂，可以重构成几个函数，分别测试Zip，ZipAppendEntry，UnZip。
2. TestZipAndUnZipAndZipAppendEntry执行后需要把所有测试创建的临时文件（text.zip）删除。

<img width="1132" alt="image" src="https://github.com/duke-git/lancet/assets/5037603/3c91ef45-506f-4712-a76d-3b49b1f8ed73">

**Comment by duke-git** [comment]
v2.2.2版本已添加
