### ISSUE TITLE
http函数包能否添加上传文件的支持

### ISSUE THREAD

**Issue by Mickls** [duke-git/lancet#109]
我发现http包内的setFormData函数仅能支持application/x-www-form-urlencoded格式，并不支持multipart/form-data格式。无法通过SendRequest函数来实现上传文件的功能。
本来是打算提一个pr看看能否直接添加支持，不过在实现后发现ut测试需要一个支持上传文件的url地址来做支撑。如果可以的话也可以给出一个相应的接口，我可以实现这个功能。
或者，考虑再多新增一个mock的工具类？

**Comment by duke-git** [comment]
@Mickls 确实需要支持mutipart，欢迎提PR🤝. 可以实现一个本地mock api. 参考以下：
```go
package main

import (
	"io"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/upload", handleUploadFile)
	http.ListenAndServe(":8090", nil)
}

func handleUploadFile(w http.ResponseWriter, r *http.Request) {
	log.Println("Content-Type: ", r.Header.Get("Content-Type"))

	if err := r.ParseMultipartForm(0); err != nil {
		log.Fatal(err)
		return
	}

	file, header, err := r.FormFile("file")
	log.Println("Upload file info: ", file, header, err)

	w.Header().Set("Content-Type", "text/json")

	io.WriteString(w, "ok")
}
```

![image](https://github.com/duke-git/lancet/assets/5037603/a5a32af3-0b45-40c7-b90a-238423e652cb)
<img width="1147" alt="image" src="https://github.com/duke-git/lancet/assets/5037603/e0f04f11-a8ee-4a28-ac9c-018d86877511">

**Comment by duke-git** [comment]
参考 #76

**Comment by Mickls** [comment]
> @Mickls 确实需要支持mutipart，欢迎提PR🤝. 可以实现一个本地mock api. 参考以下：
> 
> ```go
> package main
> 
> import (
> 	"io"
> 	"log"
> 	"net/http"
> )
> 
> func main() {
> 	http.HandleFunc("/upload", handleUploadFile)
> 	http.ListenAndServe(":8090", nil)
> }
> 
> func handleUploadFile(w http.ResponseWriter, r *http.Request) {
> 	log.Println("Content-Type: ", r.Header.Get("Content-Type"))
> 
> 	if err := r.ParseMultipartForm(0); err != nil {
> 		log.Fatal(err)
> 		return
> 	}
> 
> 	file, header, err := r.FormFile("file")
> 	log.Println("Upload file info: ", file, header, err)
> 
> 	w.Header().Set("Content-Type", "text/json")
> 
> 	io.WriteString(w, "ok")
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/5037603/245073473-a5a32af3-0b45-40c7-b90a-238423e652cb.png) <img alt="image" width="1147" src="https://user-images.githubusercontent.com/5037603/245074266-e0f04f11-a8ee-4a28-ac9c-018d86877511.png">

看上去可行，我去实现下

**Comment by duke-git** [comment]
v2.2.2版本已添加改特性
