### ISSUE TITLE
float数值ToString 后丢失精度

### ISSUE THREAD

**Issue by lsm1998** [duke-git/lancet#112]
版本 v1.2.9

复现代码如下：
`
import (
	"fmt"
	"github.com/duke-git/lancet/convertor"
	"github.com/gogf/gf/util/gconv"
	"github.com/spf13/cast"
	"testing"
)

type Demo struct {
	Amount float32 `json:"Amount"`
}

func precision(params map[string]interface{}) {
	fmt.Println(params["Amount"])
	fmt.Println(convertor.ToString(params["Amount"]))
	fmt.Println(cast.ToString(params["Amount"])) // github.com/spf13/cast
}

func TestSign(t *testing.T) {
	in := Demo{Amount: 190.99}
	precision(gconv.Map(&in)) // github.com/gogf/gf/util/gconv
}
`

输出：
`
190.99
190.99000549316406
190.99
`

只有当使用gconv转换map的时候才会复现（目前来看，没有完全测试），不确定是否是gconv库的问题，但是直接打印map内的值是正确的，且使用cast库结果也是正确的

**Comment by duke-git** [comment]
@lsm1998， 谢谢提issue，v2版本之前已修复，下个v1版本(v1.4.0)会修复该问题。

**Comment by duke-git** [comment]
v1.4.0版本已修复。
