### ISSUE TITLE
There is an ambiguity in the use of the method `fileutil.CreateDir`

### ISSUE THREAD

**Issue by el404le** [duke-git/lancet#115]
There is an ambiguity in `fileutil.CreateDir`, the incoming path must end with `/`. 
I input `/a/b/c` but create `/a/b`.
Since the function's name is `CreateDir`, the input params is dir not a file.
It is recommended that the semantics of the function be consistent with the `mkdir -p` command of the operating system, that will not cause ambiguity.
`mkdir -p /a/b/c` will create `/a/b/c` not `/a/b`

**Comment by el404le** [comment]
remove `path.Dir(absPath)` -> `os.MkdirAll(absPath, os.ModePerm)`

**Comment by duke-git** [comment]
okay, will fix it in next release.

**Comment by el404le** [comment]
> okay, will fix it in next release.

thank you!

**Comment by duke-git** [comment]
fixed in v2.2.4

**Comment by el404le** [comment]
> fixed in v2.2.4
thank you!
