### ISSUE TITLE
如何使用datetime包获得指定时区的时间呢

### ISSUE THREAD

**Issue by Will-Liang** [duke-git/lancet#120]
如何使用datetime包获得指定时区的时间呢

**Comment by duke-git** [comment]
> 如何使用datetime包获得指定时区的时间呢

目前缺少该特性，下个版本v2.2.4会添加支持，或者有好的实现也欢迎提PR。

**Comment by duke-git** [comment]
v2.2.4 datetime package函数FormatTimeToStr，FormatStrToTime，NowDateOrTime，Timestamp支持传入时区参数，
