### ISSUE TITLE
Windows下使用fileutil.zip 打包出来的内容不正确

### ISSUE THREAD

**Issue by iiiusky** [duke-git/lancet#121]
Windows下使用fileutil.zip 打包出来的内容不正确
应该是按正常目录级别打包的吧？为什么出来的不是呢？
![image](https://github.com/duke-git/lancet/assets/45157320/b20cfb0b-0b8b-4932-ac51-e776f20f6a78)

**Comment by duke-git** [comment]
@iiiusky , 你的代码和文件结构是什么。我用win10测试了一下，可以正常打包，参考下图。
![image](https://github.com/duke-git/lancet/assets/5037603/043e2ad2-eed3-4ce9-b6a9-1e2998de5ed7)

**Comment by iiiusky** [comment]
@duke-git 你用压缩软件打开，别用window自带的打开

**Comment by duke-git** [comment]
@iiiusky @OneSeven 下个版本（v2.2.5)会修复此问题。

**Comment by iiiusky** [comment]
> > @iiiusky , 你的代码和文件结构是什么。我用win10测试了一下，可以正常打包，参考下图。 ![image](https://user-images.githubusercontent.com/5037603/256406684-043e2ad2-eed3-4ce9-b6a9-1e2998de5ed7.png)
> 
> @duke-git Zip压缩确实有问题，他只会压缩一级目录，给定的path是多级的还只会压缩一级目录
> 
> ```go
> _ = fileutil.Zip("./test/1/2", "./test/1/2.zip")
> ```
> 
> ![屏幕截图 2023-08-02 170224](https://user-images.githubusercontent.com/17974392/257760803-3c2c96f6-3e95-4c21-9f8b-0693eba0f0cf.png) ![屏幕截图 2023-08-02 170306](https://user-images.githubusercontent.com/17974392/257760824-3dc9bf92-4031-496f-b4eb-4e2cb9ac2b97.png)

@OneSeven 和结构没关系，只要你是多级目录就行。你用其他rar软件打开就发现了，惨不忍睹

**Comment by duke-git** [comment]
@iiiusky v2.2.5版本修复了，可以验证一下。
