### ISSUE TITLE
IsWeekend 函数可以考虑移除

### ISSUE THREAD

**Issue by CyJaySong** [duke-git/lancet#122]
存在不同地方对周末的定义不一样，这里直接用或判断，不太合适，用户自己根据自己业务情况直接用 等于某个 Weekday 就好

**Comment by duke-git** [comment]
> 存在不同地方对周末的定义不一样，这里直接用或判断，不太合适，用户自己根据自己业务情况直接用 等于某个 Weekday 就好

可以标记为deprecated, 删除会破坏之前依赖的项目

**Comment by CyJaySong** [comment]
https://github.com/duke-git/lancet/pull/123
