### ISSUE TITLE
good project ,but get public ip is error

### ISSUE THREAD

**Issue by supermigo** [duke-git/lancet#136]
http://ip-api.com/json/ 被伟大的祖国墙了

**Comment by duke-git** [comment]
是的，这个api在国内被墙了。目前没有找到其他api.

**Comment by supermigo** [comment]
有 一个方案是[ip2region](https://github.com/lionsoul2014/ip2region)的。 但是需要xdb ，这样增加了包体。

**Comment by duke-git** [comment]
ip2region不错，但是不会为支持一个函数功能而添加第三方依赖。

**Comment by o98k-ok** [comment]
我试了 http://ip-api.com/json/   可以访问。
其他可替代的方案:
1. https://ifconfig.io/all.json
2. https://httpbin.org/ip


获取还有其他方案，留待补充。

**Comment by supermigo** [comment]
这个都不如taobao 那个请求ip的准确
