### ISSUE TITLE
设置超时时间没有效果

### ISSUE THREAD

**Issue by djsxianglei** [duke-git/lancet#137]
select {
	case <-time.After(config.retryDuration):
	case <-config.context.Done():
		return errors.New("retry is cancelled")
}

=》
select {
	case <-time.After(config.retryDuration):
                return errors.New("timeout!!")
	case <-config.context.Done():
		return errors.New("retry is cancelled")
}

如果retryDuration超时应该返回，不然会继续执行下面

**Comment by duke-git** [comment]
@djsxianglei retryDuration设置的不是超时，是两次重试的间隔时间
