### ISSUE TITLE
fileutil.MiMeType 不是很准确

### ISSUE THREAD

**Issue by vue3plugin** [duke-git/lancet#150]
我这边css、js都被返回了txt格式，ppt返回application/zip

我实际是想获得这种类似的效果 

https://raw.githubusercontent.com/cubewise-code/go-mime/master/go-mime.go

**Comment by duke-git** [comment]
> 我这边css、js都被返回了txt格式，ppt返回application/zip
> 
> 我实际是想获得这种类似的效果
> 
> https://raw.githubusercontent.com/cubewise-code/go-mime/master/go-mime.go

@vue3plugin 你提供的这个库是根据文件扩展名确定mime，反而是不准确的。可以使用如下库：
[mimetype](https://github.com/gabriel-vasile/mimetype)
