### ISSUE TITLE
读写csv文件应当考虑可以自定义分隔符

### ISSUE THREAD

**Issue by coloraven** [duke-git/lancet#155]
1、如题，csv文件涉及到分隔符的问题，如果不能自定义分隔符，那么使用第三工具包的优势并不明显。
2、而且对于有header的csv文件，读取为map切片更适合处理，
3、将map切片写入csv文件。

**Comment by duke-git** [comment]
@coloraven 欢迎提PR.

**Comment by duke-git** [comment]
v2.2.9以添加
