### ISSUE TITLE
Documentation and Go playground seem broken

### ISSUE THREAD

**Issue by EduardoOliveira** [duke-git/lancet#165]
Hi
Just an heads up Go playground fails to load and the links to the docs seem broken.

Thank you for the awesome lib :)

**Comment by duke-git** [comment]
Thanks, could you point out what Go Playground and documentation links are problematic?

**Comment by EduardoOliveira** [comment]
Looks like there was an internal problem with Go Playground yesterday.
And I can't reproduce the documentation problems.
Sorry to disturbe
