### ISSUE TITLE
OS: windows, ARCH: 386 fail to build

### ISSUE THREAD

**Issue by richelieu-yang** [duke-git/lancet#166]
<img width="1728" alt="iShot_2024-02-04_09 48 28" src="https://github.com/duke-git/lancet/assets/51251717/7b4d5aff-ef04-4a56-8c7c-7202520b63f3">

**Comment by duke-git** [comment]
@pigwantacat ,麻烦看一下这个bug. nearestPowerOfTwo有溢出。

**Comment by pigwantacat** [comment]
> @pigwantacat ,麻烦看一下这个bug. nearestPowerOfTwo有溢出。

java里的int是32位的，go里面int跟CPU有关，但也是32位或者64位，1<<30应该是没有超的

**Comment by duke-git** [comment]
v2.3.0版本已修复。
