### ISSUE TITLE
package /datastructure/set 'FromSlice' and 'Values' make me confuse

### ISSUE THREAD

**Issue by cannian1** [duke-git/lancet#186]
From an intuitive standpoint, 'FromSlice' should correspond to 'ToSlice', but the package already has a 'Values' method.

This package has undergone several function renamings recently. Is it better to keep the 'Values' method as it is or rename it? 

Should compatibility issues be taken into consideration?

**Comment by duke-git** [comment]
@cannian1, adding ToSlice is ok. for compatibility, I think we can make 'Values' method call 'ToSlice' method, and then deprecate 'Values' method, In future version 'Values' method will be removed.
