### ISSUE TITLE
Which branch should I submit to?

### ISSUE THREAD

**Issue by cannian1** [duke-git/lancet#190]
In [contributing-guide](https://github.com/duke-git/lancet#contributing-guide), It mentioned to submit to the v2 branch.

But the v2 branch doesn't have GitHub Actions.

Like #145 , PR may fail in test.

**Comment by duke-git** [comment]
> In [contributing-guide](https://github.com/duke-git/lancet#contributing-guide), It mentioned to submit to the v2 branch.
> 
> But the v2 branch doesn't have GitHub Actions.
> 
> Like #145 , PR may fail in test.

Yes, the current branch management is not standardized. To solve this problem, I suggest creating a release candidate (rc) branch to release the next version lib. All PRs should request be merged into the RC branch. At the same time, the RC branch uses GitHub Actions to run unit test tasks. After release, the rc branch will be merged into the main branch.

**Comment by cannian1** [comment]
I think this is feasible, so when would be a good time to start?

Does anyone have any other suggestions?

**Comment by duke-git** [comment]
> I think this is feasible, so when would be a good time to start?
> 
> Does anyone have any other suggestions?

I created the rc branch for release candidate. All PRs should be merged into the rc branch. The main branch will be frozen.
