### ISSUE TITLE
是否可以在system.ExecCommand函数中指定Dir属性

### ISSUE THREAD

**Issue by gaoyuan98** [duke-git/lancet#241]
现在的函数使用是这样的，源码的定义也是直接是 exec.Command
   stdout, stderr, err = system.ExecCommand("dir")
    fmt.Println("std out: ", stdout)
    fmt.Println("std err: ", stderr)

作者新增一个参数Dir属性，这样就可以用工具类跳转到指定的目录了
cmd = exec.Command("./configure", "--prefix="+pcreInstallDir)
	cmd.Dir = pcreSourceDir

**Comment by duke-git** [comment]
@gaoyuan98 ExecCommand函数的第二个参数是cmd选项控制参数，类型是func(*exec.Cmd)，可以通过这个参数设置cmd Dir属性。参考以下代码：

```go
package main

import (
	"fmt"
	"os/exec"

	"github.com/duke-git/lancet/v2/system"
)

func main() {
	stdout, _, _ := system.ExecCommand("ls", func(c *exec.Cmd) {
		c.Dir = "/a/b.c"
	})

	fmt.Println(stdout)
}
```

**Comment by gaoyuan98** [comment]
好的 感谢
