### ISSUE TITLE
Filtering Unicast IPs in netutil.GetInternalIp

### ISSUE THREAD

**Issue by SinuxLee** [duke-git/lancet#247]
I have a suggestion for improving the netutil.GetInternalIp function. Could we utilize ipNet.IP.IsLinkLocalUnicast() to filter out Unicast IPs? This would enhance the accuracy of internal IP detection.

Thank you for considering this enhancement! Looking forward to your response.

**Comment by duke-git** [comment]
> I have a suggestion for improving the netutil.GetInternalIp function. Could we utilize ipNet.IP.IsLinkLocalUnicast() to filter out Unicast IPs? This would enhance the accuracy of internal IP detection.
> 
> Thank you for considering this enhancement! Looking forward to your response.

@SinuxLee Okay, your suggestion makes sense.

**Comment by duke-git** [comment]
v2.3.3版本已修复
