### ISSUE TITLE
能否不使用 golang.org/x/exp 这个非标准库作为底层依赖

### ISSUE THREAD

**Issue by GLWJP** [duke-git/lancet#250]
../../../../../go/pkg/mod/github.com/duke-git/lancet/v2@v2.3.2/mathutil/mathutil.go:13:2: golang.org/x/exp@v0.0.0-20221208152030-732eee02a75a: missing go.sum entry for go.mod file; to add it:
	go mod download golang.org/x/exp
	
exp包
exp包是实验性的，后续可能会合并到主分支或废弃；并且不能保证与Go1的兼容性。

**Comment by duke-git** [comment]
@GLWJP 使用golang.org/x/exp包特性，主要是泛型应用，目前不好去掉，如果去掉，需要自己维护一个泛型定义集合。
