### ISSUE TITLE
Function to group slice to map of slices

### ISSUE THREAD

**Issue by muety** [duke-git/lancet#26]
I'd really like to have a function that takes a slice and a predicate function and returns a map of slices, where the keys are determined by the given predicate function. Essentially the same as [`GroupBy()` @ `samber/lo`](https://pkg.go.dev/github.com/samber/lo?utm_source=godoc#GroupBy).

**Comment by duke-git** [comment]
> I'd really like to have a function that takes a slice and a predicate function and returns a map of slices, where the keys are determined by the given predicate function. Essentially the same as [`GroupBy()` @ `samber/lo`](https://pkg.go.dev/github.com/samber/lo?utm_source=godoc#GroupBy).

Cause we already have `GroupBy` function, I add a new function and name it `GroupWith` to fit your requirement. Please check it. If fine, we will release it in v2.0.1. Please search `GroupWith` in [slice.go](https://github.com/duke-git/lancet/blob/v2/slice/slice.go).

**Comment by muety** [comment]
That's exactly what I was looking for. Thanks for the quick reaction!
