### ISSUE TITLE
v2 slice包希望提供JoinFunc

### ISSUE THREAD

**Issue by eren1017** [duke-git/lancet#260]
针对某些复杂结构的切片, 希望可以定制返回的字符串, 而不是把整个结构都转换为string

**Comment by duke-git** [comment]
> 针对某些复杂结构的切片, 希望可以定制返回的字符串, 而不是把整个结构都转换为string

下个版本可以提供JoinFunc相关函数，可以讨论下面哪个函数更合适通用：
```go
func JoinFunc[T any](slice []T, sep T, transform func(T) T) T

func JoinFunc[T any](slice []T, sep T, connector func(T, T) T) T
```

**Comment by eren1017** [comment]
> > 针对某些复杂结构的切片, 希望可以定制返回的字符串, 而不是把整个结构都转换为string
> 
> 下个版本可以提供JoinFunc相关函数，可以讨论下面哪个函数更合适通用：
> 
> ```go
> func JoinFunc[T any](slice []T, sep T, transform func(T) T) T
> 
> func JoinFunc[T any](slice []T, sep T, connector func(T, T) T) T
> ```

更偏向于 
> ```go
> func JoinFunc[T any](slice []T, sep string, transform func(T) any) string
> ```

**Comment by duke-git** [comment]
@eren1017 rc分支添加了[JoinFunc](https://github.com/duke-git/lancet/blob/rc/slice/slice.go#L1404)和[ConcatBy](https://github.com/duke-git/lancet/blob/rc/slice/slice.go#L1417)，下个版本会发布。

**Comment by duke-git** [comment]
v2.3.4添加了JoinFunc和ConcatBy

**Comment by eren1017** [comment]
> v2.3.4添加了JoinFunc和ConcatBy

slice.JoinFunc的参数transform, 函数签名能否改为func(T) any
按照现在的类型, 如果T是个结构体, 那我也只能返回个结构体, 这样意义似乎不大
