### ISSUE TITLE
condition包的TernaryOperate命名问题

### ISSUE THREAD

**Issue by ekoycut** [duke-git/lancet#264]
condition包本身就是做各中运算符的封装，按命名原则，应该只需要Ternary即可，希望把TernaryOperate改名或重命名为Ternary

**Comment by duke-git** [comment]
> Ternary

合理，但是改名会破坏兼容性，可以标记TernaryOperate为deprecated, 然后新增Ternary函数。

**Comment by duke-git** [comment]
v2分支已修改，下个版本v2.3.4会发布
