### ISSUE TITLE
random.random()方法始终返回n个a或者n个0

### ISSUE THREAD

**Issue by coder-liyang** [duke-git/lancet#265]
RandString(),RandNumeral()等方法的底层方法都是random(),不知道什么原因引起的,从某一刻起,随机出来的内容就固定了,随机字符串就固定是n个a,随机数字就固定是n个0,重新build一下就又没问题了.
![图片](https://github.com/user-attachments/assets/26b61324-593b-4f42-a181-089e897815ba)
![图片](https://github.com/user-attachments/assets/0e2276a0-3fec-4e4c-a971-7bc113ce3823)

**Comment by duke-git** [comment]
@coder-liyang 应该是调用random前，随机数种子没有变化，这个后续会修复。临时方案是调用RandString(),RandNumeral()等方法前加上rand.Seed(time.Now().UnixNano())

**Comment by feng6917** [comment]
当在并发或者分布式系统中进行随机数生成时，仅通过时间戳作为种子进行随机出的数值并不能保证，因为在同一时间可能会生成多个随机数；如果使用时间戳加上线程ID可以避免这个问题。
![image](https://github.com/user-attachments/assets/a9bf84d1-5d59-42db-8ec2-439a5ca08b70)

**Comment by duke-git** [comment]
fixed in v2.3.4
