### ISSUE TITLE
插入排序算法有问题 algorithm.InsertionSort

### ISSUE THREAD

**Issue by tesla-wu** [duke-git/lancet#27]
# 
请检查一下 algorithm.InsertionSort(peoples, comparator)  这个插入排序算法有问题，获取到排序后的元素都是重复的

```
    var peoples = []people{
        {Name: "a", Age: 20},
        {Name: "b", Age: 10},
        {Name: "c", Age: 17},
        {Name: "d", Age: 8},
        {Name: "e", Age: 28},
    }
    comparator := &peopleAgeComparator{}
    sortedPeople := algorithm.InsertionSort(peoples, comparator)
    fmt.Println(sortedPeople) 
    // out:  [{a 20} {a 20} {a 20} {a 20} {a 20}]
```

**Comment by tesla-wu** [comment]
![image](https://user-images.githubusercontent.com/16518125/160229131-5f013f73-8337-4210-8e09-83a0cef58eff.png)

算法测试目标不一致

**Comment by duke-git** [comment]
> 请检查一下 algorithm.InsertionSort(peoples, comparator) 这个插入排序算法有问题，获取到排序后的元素都是重复的
> 
> ```
>     var peoples = []people{
>         {Name: "a", Age: 20},
>         {Name: "b", Age: 10},
>         {Name: "c", Age: 17},
>         {Name: "d", Age: 8},
>         {Name: "e", Age: 28},
>     }
>     comparator := &peopleAgeComparator{}
>     sortedPeople := algorithm.InsertionSort(peoples, comparator)
>     fmt.Println(sortedPeople) 
>     // out:  [{a 20} {a 20} {a 20} {a 20} {a 20}]
> ```



> 请检查一下 algorithm.InsertionSort(peoples, comparator) 这个插入排序算法有问题，获取到排序后的元素都是重复的
> 
> ```
>     var peoples = []people{
>         {Name: "a", Age: 20},
>         {Name: "b", Age: 10},
>         {Name: "c", Age: 17},
>         {Name: "d", Age: 8},
>         {Name: "e", Age: 28},
>     }
>     comparator := &peopleAgeComparator{}
>     sortedPeople := algorithm.InsertionSort(peoples, comparator)
>     fmt.Println(sortedPeople) 
>     // out:  [{a 20} {a 20} {a 20} {a 20} {a 20}]
> ```

@tesla-wu 谢谢，已在v2分支修复，将会发布到v2.0.2 release. 请查阅 SelectionSort [sorter.go](https://github.com/duke-git/lancet/blob/main/algorithm/sorter.go).
