### ISSUE TITLE
structs.ToMap() 方法对slice 类型转化非 []any 类型

### ISSUE THREAD

**Issue by LittleMoreInteresting** [duke-git/lancet#270]
https://go.dev/play/p/yvOcWp9IcOj
![image](https://github.com/user-attachments/assets/6a1c6a88-1336-4ea0-9897-4b8fd336f106)

**Comment by duke-git** [comment]
@LittleMoreInteresting 什么意思，下面是我的执行结果
[https://go.dev/play/p/yvOcWp9IcOj](https://go.dev/play/p/yvOcWp9IcOj)
<img width="693" alt="image" src="https://github.com/user-attachments/assets/51d60299-4a8d-42ac-a0ae-b3c9dd02ff27">

**Comment by LittleMoreInteresting** [comment]
自动回复邮件。您好，感谢您的来信。我会尽快查阅您的邮件并及时给您回复。

**Comment by LittleMoreInteresting** [comment]
期望m2["name"] 返回一个 []any 类型 目前返回的是一下 []int

**Comment by duke-git** [comment]
ToMap返回的是map[string]any类型，不会去修改any内部类型。如果期望m2["name"]返回一个[]any类型，在struct定义Name字段为[]any类型
