### ISSUE TITLE
random.go 中的 math.MaxInt 未定义

### ISSUE THREAD

**Issue by ylinbo2013** [duke-git/lancet#273]
go版本：go1.16
lancet@v1.4.4
random.go 中的 math.MaxInt 未定义

**Comment by duke-git** [comment]
math.MaxInt在go1.17引入，下个版本（v1.4.5）会修复该问题。

**Comment by ylinbo2013** [comment]
别忘了main 版本也要修改，math.MaxInt这个常量在Go 1.13版本中被移除

**Comment by duke-git** [comment]
Fixed in v2.3.4
