### ISSUE TITLE
lancet@v1.4.5 不兼容go@1.16的部分bug

### ISSUE THREAD

**Issue by ylinbo2013** [duke-git/lancet#275]
go版本:v1.16
lancet@v1.4.5
bug如下：
compare下的reflect.CanConvert 未定义
strutil下的strings.Cut 未定义

**Comment by ylinbo2013** [comment]
提个建议：针对这种goang不同版本的支持，可以用gvm 切换不同版本来查看各个版本兼容的情况！

**Comment by ylinbo2013** [comment]
我用goland编辑器每个文件打开了一下，看到有标红的地方，说明这个函数不存在！因此提到了上面2个bug! 这个很容易就发现了！希望作者再仔细一些！作者辛苦了！

**Comment by duke-git** [comment]
@ylinbo2013 v1.4.6版本修复了
