### ISSUE TITLE
www.golancet.cn文档中，类型转换ToJson示例存在错误

### ISSUE THREAD

**Issue by tongque0** [duke-git/lancet#276]
我在 [Lancet ](https://www.golancet.cn) 上查看 `convertor` 包的 `ToJson` 函数文档时，发现示例代码中存在错误。示例代码在调用 `ToJson` 函数时没有加上包名前缀，这将导致编译错误。

**当前示例:**
![image](https://github.com/user-attachments/assets/2813a1a2-98ec-4cdd-8a8d-a359bcc6a19b)

**修正后的示例:**

```go
package main

import (
    "fmt"
    "github.com/duke-git/lancet/v2/convertor"
)

func main() {
    aMap := map[string]int{"a": 1, "b": 2, "c": 3}
    result, err := convertor.ToJson(aMap)

    if err != nil {
        fmt.Printf("%v", err)
    }

    fmt.Println(result)

    // Output:
    // {"a":1,"b":2,"c":3}
}
```

**建议:**

请更新文档中的示例代码，以避免用户在复制示例代码时遇到编译错误。

感谢您的关注和维护！

**Comment by duke-git** [comment]
更新了
