### ISSUE TITLE
找了一遍，发现没有 func RemoveString(slice []string, str string) []string

### ISSUE THREAD

**Issue by J4sonZ** [duke-git/lancet#280]
func RemoveString(slice []string, str string) []string {
	result := make([]string, 0, len(slice))
	for _, item := range slice {
		if item != str {
			result = append(result, item)
		}
	}
	return result
}

**Comment by duke-git** [comment]
@J4sonZ , 使用slice.Filter实现。

**Comment by J4sonZ** [comment]
> @J4sonZ , 使用slice.Filter实现。

感觉上是没问题的，我只是提个建议哈， RemoveString(slice []string, str string) []string 这个功能常用级别应该非常 top，如果是 slice.Filter，每次使用的时候带一个函数在参数中感觉不够简洁。有一个库 goutils，把这个功能单独抽出来
![image](https://github.com/user-attachments/assets/adce0991-8d62-42ff-a40e-576790e50f68)

**Comment by duke-git** [comment]
@J4sonZ RemoveString不是通用函数，如果要实现RemoveString，还需实现RemoveInt, RemoveFloat64, RemoveXXX. 实现泛型版本：RemoveT[T comparable](slice []T, item T) []T. 这个T还要求是comparable的，功能没有slice.Filter强大。
