### ISSUE TITLE
建议添加 decimal的处理

### ISSUE THREAD

**Issue by a-dwarf** [duke-git/lancet#34]
https://github.com/shopspring/decimal/blob/master/decimal.go

**Comment by duke-git** [comment]
@a-dwarf 好的，未来版本回添加decimal处理。

**Comment by duke-git** [comment]
@a-dwarf, 后期会添加，或者您也可以fork仓库后自行开发，然后提pr merge.

**Comment by lifetin** [comment]
支付一下. 添加decimal迫在眉睫!!!!!

**Comment by duke-git** [comment]
> 支付一下. 添加decimal迫在眉睫!!!!!

@lifetin [decimal](https://github.com/shopspring/decimal) 这个库已经很完善了，再写一个功能很难比这个好。
