### ISSUE TITLE
文件处理目录

### ISSUE THREAD

**Issue by shuqingzai** [duke-git/lancet#35]
好像没有创建目录(createDir)的方法？

**Comment by duke-git** [comment]
> 好像没有创建目录(createDir)的方法？

@shuqingzai CreateDir方法已添加到v2分支中，将在下一个版本发布。

**Comment by duke-git** [comment]
v2.0.9版本已添加CreateDir函数。

**Comment by wxl2578** [comment]
如果作者有时间，文件处理模块希望能在完善一些，比如一些写的便捷操作

**Comment by duke-git** [comment]
> 如果作者有时间，文件处理模块希望能在完善一些，比如一些写的便捷操作

@wxl2578, 可以后续会完善文件操作功能。
