### ISSUE TITLE
跟https://github.com/samber/lo有什么区别或优势？

### ISSUE THREAD

**Issue by feeops** [duke-git/lancet#38]
跟https://github.com/samber/lo有什么区别或优势？

**Comment by duke-git** [comment]
> 跟[https://github.com/samber/lo有什么区别或优势？](https://github.com/samber/lo%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%E6%88%96%E4%BC%98%E5%8A%BF%EF%BC%9F)

@feeops 参考以下：
1. lancet的创建时间比lo早。
2. 功能区别：lo类似lodash.js。包括对数组，切片，struct，函数和并发的等操作的支持。lancet范围更广泛，除了这些功能，还包括：netutil, validator, fileutil, 加解密，数据结构和算法等。lancet定位目标是java中的apache common包。
