### ISSUE TITLE
about AesCbcEncrypt

### ISSUE THREAD

**Issue by qingtao** [duke-git/lancet#42]
关于AesCbcEncrypt()和AesCbcDecrypt()中iv使用 key[:blockSize]是基于什么决定的，这样是不是和其他语言的对接不够准确呢？

**Comment by duke-git** [comment]
> 关于AesCbcEncrypt()和AesCbcDecrypt()中iv使用 key[:blockSize]是基于什么决定的，这样是不是和其他语言的对接不够准确呢？

@qingtao 已在v2分支中调整了这两个函数的iv取值（iv取密文的前16个字节）。参考[AesCbcEncrypt](https://github.com/duke-git/lancet/blob/cece13e929934bd6f5ccfcaaf6e73e439a35493d/cryptor/aes.go#L56)。下个版本会发布修复。

**Comment by duke-git** [comment]
已在v2.1.3中调整。
