### ISSUE TITLE
可搜索的lancet文档

### ISSUE THREAD

**Issue by UvDream** [duke-git/lancet#57]
最近用到这个库,发现文档查找挺麻烦的,所以把文档搬过去做了一个在线可搜索的文档库
[lancet-docs](https://uvdream.github.io/lancet-docs/)
希望能帮到用到这个库的小伙伴
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/33121872/192976028-81c1b9bd-29b6-48df-bc57-16e438ca09db.png">
algolia 搜索引擎还在对接中,等对接完成,搜索更友好快捷准确!

**Comment by duke-git** [comment]
👍太赞了！也更新了readme.
![image](https://user-images.githubusercontent.com/5037603/193012441-457f2857-ea4a-43c5-91dd-703e3b0a7a48.png)

**Comment by UvDream** [comment]
嘿嘿,举手之劳,方便大家使用!
