### ISSUE TITLE
建议数据结构map加个遍历操作

### ISSUE THREAD

**Issue by LunacyZeus** [duke-git/lancet#58]
类似goframe提供的类似设计
https://goframe.org/pages/viewpage.action?pageId=30736711

不然只有get和put 这好像不太方便后续操作

然后能加个并发控制的就最好了

**Comment by duke-git** [comment]
> 类似goframe提供的类似设计 https://goframe.org/pages/viewpage.action?pageId=30736711
> 
> 不然只有get和put 这好像不太方便后续操作
> 
> 然后能加个并发控制的就最好了
v2分支上，hashmap加入了Iterate，Keys, Valuse方法，后续会加上并发控制。

**Comment by duke-git** [comment]
v2.1.7支持map遍历
