### ISSUE TITLE
aes 偏移量

### ISSUE THREAD

**Issue by rangujie** [duke-git/lancet#61]
iv变量可以改成和key一样吗？现在实现的aes加密 js解密失败

**Comment by duke-git** [comment]
原实现：可以实现go aes加密 js解密.
```go
func AesCbcEncrypt(data, key []byte) []byte {
	block, _ := aes.NewCipher(key)
	blockSize := block.BlockSize()
	data = pkcs7Padding(data, blockSize)
	blockMode := cipher.NewCBCEncrypter(block, key[:blockSize])

	encrypted := make([]byte, len(data))
	blockMode.CryptBlocks(encrypted, data)

	return encrypted
}

func AesCbcDecrypt(encrypted, key []byte) []byte {
	block, _ := aes.NewCipher(key)

	blockSize := block.BlockSize()
	blockMode := cipher.NewCBCDecrypter(block, key[:blockSize])

	decrypted := make([]byte, len(encrypted))
	blockMode.CryptBlocks(decrypted, encrypted)
	decrypted = pkcs7UnPadding(decrypted)

	return decrypted
}
```
参考[issues #42](https://github.com/duke-git/lancet/issues/42)

**Comment by rangujie** [comment]
> 原实现：可以实现go aes加密 js解密.
> 
> ```go
> func AesCbcEncrypt(data, key []byte) []byte {
> 	block, _ := aes.NewCipher(key)
> 	blockSize := block.BlockSize()
> 	data = pkcs7Padding(data, blockSize)
> 	blockMode := cipher.NewCBCEncrypter(block, key[:blockSize])
> 
> 	encrypted := make([]byte, len(data))
> 	blockMode.CryptBlocks(encrypted, data)
> 
> 	return encrypted
> }
> 
> func AesCbcDecrypt(encrypted, key []byte) []byte {
> 	block, _ := aes.NewCipher(key)
> 
> 	blockSize := block.BlockSize()
> 	blockMode := cipher.NewCBCDecrypter(block, key[:blockSize])
> 
> 	decrypted := make([]byte, len(encrypted))
> 	blockMode.CryptBlocks(decrypted, encrypted)
> 	decrypted = pkcs7UnPadding(decrypted)
> 
> 	return decrypted
> }
> ```
> 
> 参考[issues #42](https://github.com/duke-git/lancet/issues/42)

好呢，谢谢
