### ISSUE TITLE
How to get in touch regarding a security concern?

### ISSUE THREAD

**Issue by cokeBeer** [duke-git/lancet#62]
Hello 👋

I found a potential security issue in lancet, how can I get in touch with you in a private way and submit my security report?

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

**Comment by duke-git** [comment]
@cokeBeer, Thanks, it's a good advice. I have added a security policy to lancet. Please please see [security policy](https://github.com/duke-git/lancet/security/policy)
