### ISSUE TITLE
slice chunk的坑

### ISSUE THREAD

**Issue by feeops** [duke-git/lancet#63]
```
package main

import (
	"fmt"

	"github.com/duke-git/lancet/v2/slice"
	"github.com/samber/lo"
)

func main() {
	arr := []string{"a", "b", "c"}
	fmt.Println(slice.Chunk(arr, 10))
	fmt.Println(lo.Chunk(arr, 10))
}
```

输出
```
[[a] [b] [c]]

[[a b c]]
```

当chunk长度大于slice长度时，lo库的处理逻辑是正确的

**Comment by duke-git** [comment]
> ```
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/duke-git/lancet/v2/slice"
> 	"github.com/samber/lo"
> )
> 
> func main() {
> 	arr := []string{"a", "b", "c"}
> 	fmt.Println(slice.Chunk(arr, 10))
> 	fmt.Println(lo.Chunk(arr, 10))
> }
> ```
> 
> 输出
> 
> ```
> [[a] [b] [c]]
> 
> [[a b c]]
> ```
> 
> 当chunk长度大于slice长度时，lo库的处理逻辑是正确的

@feeops v2分支上已修复[chunk](https://github.com/duke-git/lancet/blob/80cbbdc7871e96c832be2dbf89370c4a909a6aee/slice/slice.go#L38), 下个版本会更新

**Comment by duke-git** [comment]
v2.1.11版本已修复。
