### ISSUE TITLE
ExecCommand   是否支持  windows command

### ISSUE THREAD

**Issue by ch3nnn** [duke-git/lancet#65]
在使用过程中遇到 windows 环境下需要执行系统命令发现没有相关代码

**Comment by duke-git** [comment]
> 在使用过程中遇到 windows 环境下需要执行系统命令发现没有相关代码

system.ExecCommand方法目前在windows下执行会有问题（出现乱码）。windows下CMD的编码是GBK, ExecCommand方法需要做GBK编码转换，下个版本(v2.1.12)会解决。

**Comment by duke-git** [comment]
已修复
