### ISSUE TITLE
列表能否增加 foreach或者 Iterator 操作，还有两个集合求交集，差集

### ISSUE THREAD

**Issue by zundaren** [duke-git/lancet#68]

**Comment by zundaren** [comment]
1.list队列等等能否增加 foreach或者 Iterator 操作，还有两个集合求交集，差集
2.对象赋值转换，对象转map，map 转对象，深拷贝等等功能

**Comment by duke-git** [comment]
> 1.list队列等等能否增加 foreach或者 Iterator 操作，还有两个集合求交集，差集，集合按条件分组k-[]v, 大部分功能slice都有，每次使用都要先转成 slice在操做很繁琐 2.对象赋值转换，对象转map，map 转对象，深拷贝等等功能

v2.1.14版本，datastructure/list/list.go, 新添加函数: Difference, SymmetricDifference, RetainAll, DeleteAll, ForEach, Iterator, ListToMap

**Comment by duke-git** [comment]
v2.1.15版本增加convertor.DeepClone(src)，支持深拷贝。
