### ISSUE TITLE
go升级问题

### ISSUE THREAD

**Issue by PengFei-io** [duke-git/lancet#72]
这个工具如果使用go使用低版本进行开发了大量代码，后续升级了高版本的go，会影响原有使用低版本lancet的使用吗。或者也可以同时把lancet升级了吗。

**Comment by duke-git** [comment]
> 这个工具如果使用go使用低版本进行开发了大量代码，后续升级了高版本的go，会影响原有使用低版本lancet的使用吗。或者也可以同时把lancet升级了吗。

lancet v1.x.x兼容go1.6及以上版本，v2.x.x兼容go1.8及以上版本。如果项目使用的go版本在这个范围内都都不会有影响，除非go本身出现兼容性问题。

**Comment by PengFei-io** [comment]
好的，感谢回复，我看2个版本是可以同时运行的.
