### ISSUE TITLE
AesEcbEncrypt 加密方式 问题

### ISSUE THREAD

**Issue by longrbl** [duke-git/lancet#73]
在采用go版本的AesEcbEncrypt 进行加密和AesEcbDecrypt 解密没有问题 （key长度16位）
但是用24 和32位的加密方法加密的结果 在第三方平台无法解密，参考网站结果：http://tool.chacuo.net/cryptaes

**Comment by longrbl** [comment]
> 在采用go版本的AesEcbEncrypt 进行加密和AesEcbDecrypt 解密没有问题 （key长度16位） 但是用24 和32位的加密方法加密的结果 在第三方平台无法解密，参考网站结果： [http://tool.chacuo.net/cryptaes ](http://tool.chacuo.net/cryptaes)

修改方案：
修改文件github.com\duke-git\lancet\v2@v2.1.6\cryptor\aes.go
20行
	cipher, _ := aes.NewCipher(generateAesKey(key)) 修改成cipher, _ := aes.NewCipher(key)
这样就可以解决aes不能加密后解密24，32 key的问题

**Comment by duke-git** [comment]
> > 在采用go版本的AesEcbEncrypt 进行加密和AesEcbDecrypt 解密没有问题 （key长度16位） 但是用24 和32位的加密方法加密的结果 在第三方平台无法解密，参考网站结果： [http://tool.chacuo.net/cryptaes ](http://tool.chacuo.net/cryptaes)
> 
> 修改方案： 修改文件github.com\duke-git\lancet\v2@v2.1.6\cryptor\aes.go 20行 cipher, _ := aes.NewCipher(generateAesKey(key)) 修改成cipher, _ := aes.NewCipher(key) 这样就可以解决aes不能加密后解密24，32 key的问题

@longrbl 谢谢，下个版本(v2.1.5)会修复此问题。

**Comment by duke-git** [comment]
v1.3.6和v2.1.15及以上版本已修复。
