### ISSUE TITLE
strutil中Pad函数存在问题

### ISSUE THREAD

**Issue by tomatocuke** [duke-git/lancet#74]
1. padStr为空字符串时会引起越界报错。(我看js在填充空字符串时不填充)
2. strings.Repeat(padStr, size-len1) 可能造成巨大浪费。例如 字符串 Hello后补充 World 到 100字符，World会Repeat为 5*(100-5)=475个字符。

例如
```go
func PadEnd(source string, size int, padStr string) string {
	len1 := len(source)
	len2 := len(padStr)

	if len1 >= size || padStr == "" {
		return source
	}

	if len1+len2 >= size {
		return source + padStr[:size-len1]
	}

	fill := strings.Repeat(padStr, (size-len1)/len2+1)[:size-len1]
	return source + fill[:size-len1]
}
```

**Comment by duke-git** [comment]
> 1. padStr为空字符串时会引起越界报错。(我看js在填充空字符串时不填充)
> 2. strings.Repeat(padStr, size-len1) 可能造成巨大浪费。例如 字符串 Hello后补充 World 到 100字符，World会Repeat为 5*(100-5)=475个字符。
> 
> 例如
> 
> ```go
> func PadEnd(source string, size int, padStr string) string {
> 	len1 := len(source)
> 	len2 := len(padStr)
> 
> 	if len1 >= size || padStr == "" {
> 		return source
> 	}
> 
> 	if len1+len2 >= size {
> 		return source + padStr[:size-len1]
> 	}
> 
> 	fill := strings.Repeat(padStr, (size-len1)/len2+1)[:size-len1]
> 	return source + fill[:size-len1]
> }
> ```

v2分之已修复，下个版本会发布。
