### ISSUE TITLE
random 相关函数实现，高运算并发问题

### ISSUE THREAD

**Issue by OneSeven** [duke-git/lancet#75]
```
rand.New(rand.NewSource(time.Now().UnixNano()))
```
使用纳秒作为种子，并发/运算很快的情况下，同一纳秒下，会生成一样的结果

直接替换成rand.xxx()，没有此问题

**Comment by duke-git** [comment]
> rand.NewSource
v2分支已修复，参考[random.go -> RandInt](https://github.com/duke-git/lancet/blob/v2/random/random.go), 下个版本v2.1.16会发布。
