### ISSUE TITLE
windows下执行system.ExecCommand()问题

### ISSUE THREAD

**Issue by zundaren** [duke-git/lancet#86]
windows下执行system.ExecCommand()会先弹出一个窗口在执行命令，然后这个窗口关闭，
有没有选项让用户选择： 要弹窗，后台直接执行不显示弹窗

我的命令  explorer.exe /e,/select,F:\

**Comment by Nothing-no** [comment]
1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"

**Comment by duke-git** [comment]
> 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"
> 2. 请看[[FEATURE] system 中添加Option #87](https://github.com/duke-git/lancet/pull/87)

👍，下午会发布v2.1.19版本, 包含这个修复。

**Comment by zundaren** [comment]
> > 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"
> > 2. 请看[[FEATURE] system 中添加Option #87](https://github.com/duke-git/lancet/pull/87)
> 
> 👍，下午会发布v2.1.19版本, 包含这个修复。

太棒了

**Comment by duke-git** [comment]
> > > 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"
> > > 2. 请看[[FEATURE] system 中添加Option #87](https://github.com/duke-git/lancet/pull/87)
> > 
> > 
> > 👍，下午会发布v2.1.19版本, 包含这个修复。
> 
> 太棒了

v2.1.19版本已发布。

**Comment by zundaren** [comment]
> > > > 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"
> > > > 2. 请看[[FEATURE] system 中添加Option #87](https://github.com/duke-git/lancet/pull/87)
> > > 
> > > 
> > > 👍，下午会发布v2.1.19版本, 包含这个修复。
> > 
> > 
> > 太棒了
> 
> v2.1.19版本已发布。

当前发布的版本我使用 mac 开发编译不了，要不要做成空方法形式
<img width="688" alt="image" src="https://user-images.githubusercontent.com/44863479/232424904-6c1af50e-f2d3-4fc2-b32d-ffe9cdb8a7d6.png">

//go:build windows
package system
import (
	"os/exec"
	"syscall"
)

func WithWinHide() Option {
	return func(c *exec.Cmd) {
		if c.SysProcAttr == nil {
			c.SysProcAttr = &syscall.SysProcAttr{
				HideWindow: true,
			}
		} else {
			c.SysProcAttr.HideWindow = true
		}
	}
}


//go:build darwin
package system
import (
	"os/exec"
	"syscall"
)

func WithWinHide() Option {
	return func(c *exec.Cmd) {
		
	}
}

**Comment by duke-git** [comment]
> > > > > 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"
> > > > > 2. 请看[[FEATURE] system 中添加Option #87](https://github.com/duke-git/lancet/pull/87)
> > > > 
> > > > 
> > > > 👍，下午会发布v2.1.19版本, 包含这个修复。
> > > 
> > > 
> > > 太棒了
> > 
> > 
> > v2.1.19版本已发布。
> 
> 当前发布的版本我使用 mac 开发编译不了，要不要做成空方法形式 <img alt="image" width="688" src="https://user-images.githubusercontent.com/44863479/232424904-6c1af50e-f2d3-4fc2-b32d-ffe9cdb8a7d6.png">
> 
> //go:build windows package system import ( "os/exec" "syscall" )
> 
> func WithWinHide() Option { return func(c *exec.Cmd) { if c.SysProcAttr == nil { c.SysProcAttr = &syscall.SysProcAttr{ HideWindow: true, } } else { c.SysProcAttr.HideWindow = true } } }
> 
> //go:build darwin package system import ( "os/exec" "syscall" )
> 
> func WithWinHide() Option { return func(c *exec.Cmd) {
> 
> ```
> }
> ```
> 
> }

可以，v2修复了，下个版本(v2.1.20)会发布。

**Comment by Nothing-no** [comment]
> 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"

> 2. 如果是想要执行的时候去掉，这个

> mac 开发编译不了，
失策，macOS我没用过~~

**Comment by Nothing-no** [comment]
> > > > > > 1. 如果是编译程序本身的话，可以在编译的时候，使用 --ldflags "-H=windowsgui"
> > > > > > 2. 请看[[FEATURE] system 中添加Option #87](https://github.com/duke-git/lancet/pull/87)
> > > > > 
> > > > > 
> > > > > 👍，下午会发布v2.1.19版本, 包含这个修复。
> > > > 
> > > > 
> > > > 太棒了
> > > 
> > > 
> > > v2.1.19版本已发布。
> > 
> > 
> > 当前发布的版本我使用 mac 开发编译不了，要不要做成空方法形式 <img alt="image" width="688" src="https://user-images.githubusercontent.com/44863479/232424904-6c1af50e-f2d3-4fc2-b32d-ffe9cdb8a7d6.png">
> > //go:build windows package system import ( "os/exec" "syscall" )
> > func WithWinHide() Option { return func(c *exec.Cmd) { if c.SysProcAttr == nil { c.SysProcAttr = &syscall.SysProcAttr{ HideWindow: true, } } else { c.SysProcAttr.HideWindow = true } } }
> > //go:build darwin package system import ( "os/exec" "syscall" )
> > func WithWinHide() Option { return func(c *exec.Cmd) {
> > ```
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> 可以，v2分支修复了，下个版本(v2.1.20)会发布。

失策，macOS我没有用过~~，看来得找个时间了解一下

**Comment by duke-git** [comment]
v2.1.20版本已发布，加入WithWinHide空方法。
