### ISSUE TITLE
convertor.CopyProperties()无法赋值结构名不一致的属性，

### ISSUE THREAD

**Issue by zundaren** [duke-git/lancet#91]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/44863479/233241043-ff8ddc2f-20c3-43e5-9c1c-1649db3d8cfd.png">
<img width="677" alt="image" src="https://user-images.githubusercontent.com/44863479/233241091-c8d5f5f4-d172-4b29-80d6-21fe68879693.png">
<img width="589" alt="image" src="https://user-images.githubusercontent.com/44863479/233241134-422967b0-0a82-4114-9a54-5be3b334c462.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/44863479/233241206-f44eabab-6137-4bdf-ab60-523dece2e201.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/44863479/233241278-c8b74a22-7f53-45df-904c-ea486a56ff31.png">

期望属性值有就赋值，没有就跳过，和只要数据结构，字段一样，像 string int这种能转换的要是也能自动转更好了

**Comment by zundaren** [comment]
gf框架的复制是正常的，转到这个新方法出 bug

**Comment by duke-git** [comment]
@zundaren 下周发布v2.1.20会修复这个问题。

**Comment by yguilai** [comment]
感觉更像是feature :see_no_evil:
