### ISSUE TITLE
TestZipAndUnZip not remove the temp file successfully.

### ISSUE THREAD

**Issue by dablelv** [duke-git/lancet#92]
When i run the test unit function TestZipAndUnZip on Windows, I found the os.Remove not remove the temp file successfully beacause it occurred an error "The process cannot access the file because it is being used by another process".

**Comment by duke-git** [comment]
@dablelv，你的os版本和go版本是多少，我在win10上, go1.20.3测试TestZipAndUnZip可以通过。
![image](https://user-images.githubusercontent.com/5037603/233914061-e160e3a8-0977-4746-9bf8-a0ff52376624.png)

在windows中文件处于打开状态下，此时删除文件会报错。应该是没有close文件，删除会报这个错误。参考[#58860](https://github.com/golang/go/issues/58860), [#10781](https://github.com/gohugoio/hugo/issues/10781)
