### ISSUE TITLE
IsPingConnected

### ISSUE THREAD

**Issue by zundaren** [duke-git/lancet#93]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/44863479/234554981-630dd50a-c683-400d-922a-6eb0d44c6353.png">
windows 和 mac 以及 linux 参数都是不一样的，这个最好查下资料在发布
windows ping -n 6
mac ping -c 6

**Comment by duke-git** [comment]
@zundaren下个版本(v2.2.0)会修复

**Comment by duke-git** [comment]
v2.2.0已发布
