### ISSUE TITLE
问哈有没有数据脱敏的工具，像身份证，手机，密码等

### ISSUE THREAD

**Issue by zundaren** [duke-git/lancet#98]
全部转成*， 部分转成*，自定义转换策略

**Comment by duke-git** [comment]
> 全部转成*， 部分转成*，自定义转换策略

@zundaren 下个版本可以支持类似一下函数：
```go
func HideString(str string, start, end int, replaceChar string) string
```

**Comment by duke-git** [comment]
v2.2.1已发布，包含[HideString函数](https://github.com/duke-git/lancet/blob/main/docs/strutil_zh-CN.md#HideString)
