### ISSUE TITLE
datetime init error

### ISSUE THREAD

**Issue by NLBSN** [duke-git/lancet#99]
"yyyy-mm-dd hh":       "2006-01-02 15:04"   --->   "yyyy-mm-dd hh":       "2006-01-02 15",

**Comment by duke-git** [comment]
已修复，[PR#100](https://github.com/duke-git/lancet/pull/100), 下个版本会发布

**Comment by duke-git** [comment]
已修复，[PR#100](https://github.com/duke-git/lancet/pull/100), 下个版本会发布

**Comment by duke-git** [comment]
v2.2.1版本已发布，包含本issue的修复
